parameters:
    darvin_user.admin.metadata.class: Darvin\AdminBundle\Metadata\Metadata

    darvin_user.admin.metadata.user.entity: Darvin\UserBundle\Entity\BaseUser

services:
    darvin_user.admin.metadata.user:
        class:   %darvin_user.admin.metadata.class%
        factory: [ "@darvin_admin.metadata.factory", createMetadata ]
        public:  false
        arguments:
            - %darvin_user.admin.metadata.user.entity%
            - %darvin_user.admin_config%
        tags:
            - { name: darvin_admin.metadata }
