parameters:
    darvin_user.admin.view_widget.user_roles.class: Darvin\UserBundle\Admin\View\UserRolesWidget

services:
    _defaults:
        public: true

    darvin_user.admin.view_widget.user_roles:
        class:  '%darvin_user.admin.view_widget.user_roles.class%'
        parent: darvin_admin.view.widget.abstract
        public: false
        arguments:
            - '@darvin_user.role.configuration'
            - '@translator'
        tags:
            - { name: darvin_admin.view_widget }
