parameters:
    darvin_user.admin.metadata.user.entity: Darvin\UserBundle\Entity\BaseUser

    darvin_user.admin.security_configuration.class: Darvin\UserBundle\Admin\Security\Configuration

services:
    darvin_user.admin.metadata.user:
        parent: darvin_admin.metadata.abstract
        arguments:
            - "%darvin_user.user_class%"
            - "%darvin_user.admin_config%"
        tags:
            - { name: darvin_admin.metadata }

    darvin_user.admin.security_configuration:
        class: "%darvin_user.admin.security_configuration.class%"
        tags:
            - { name: darvin_admin.security_configuration }
