parameters:
    darvin_user.admin.view_widget.user_roles.class: Darvin\UserBundle\Admin\View\UserRolesWidget

services:
    darvin_user.admin.view_widget.user_roles:
        class:  "%darvin_user.admin.view_widget.user_roles.class%"
        parent: darvin_admin.view.widget.abstract
        calls:
            - [ setRoleConfig, [ "@darvin_user.configuration.roles" ] ]
            - [ setTranslator, [ "@translator" ] ]
        tags:
            - { name: darvin_admin.view_widget }
