parameters:
    darvin_user.authentication.success_handler.class: Darvin\UserBundle\Authentication\SuccessHandler

services:
    darvin_user.authentication.success_handler:
        class:  '%darvin_user.authentication.success_handler.class%'
        parent: security.authentication.success_handler
