parameters:
    darvin_user.configuration.class: Darvin\UserBundle\Configuration\UserConfiguration

services:
    _defaults:
        public: true

    darvin_user.configuration:
        class: '%darvin_user.configuration.class%'
        tags:
            - { name: darvin_config.configuration }
