parameters:
    darvin_user.password_reset_token.factory.class: Darvin\UserBundle\PasswordResetToken\PasswordResetTokenFactory

    darvin_user.password_reset_token.form.factory.class: Darvin\UserBundle\Form\Factory\PasswordResetTokenFormFactory

    darvin_user.password_reset_token.form.handler.class: Darvin\UserBundle\Form\Handler\PasswordResetTokenFormHandler

    darvin_user.password_reset_token.form.renderer.class: Darvin\UserBundle\Form\Renderer\PasswordResetTokenFormRenderer

services:
    darvin_user.password_reset_token.factory:
        class: %darvin_user.password_reset_token.factory.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - %darvin_user.password_reset_token_lifetime%

    darvin_user.password_reset_token.form.factory:
        class: %darvin_user.password_reset_token.form.factory.class%
        arguments:
            - "@security.authentication_utils"
            - "@form.factory"
            - "@router"

    darvin_user.password_reset_token.form.handler:
        class: %darvin_user.password_reset_token.form.handler.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
            - "@darvin_utils.flash.notifier"

    darvin_user.password_reset_token.form.renderer:
        class: %darvin_user.password_reset_token.form.renderer.class%
        arguments:
            - "@darvin_user.password_reset_token.form.factory"
            - "@templating"
