parameters:
    darvin_user.password_reset_token.factory.class: Darvin\UserBundle\PasswordResetToken\PasswordResetTokenFactory

    darvin_user.password_reset_token.form.factory.class: Darvin\UserBundle\Form\Factory\PasswordResetTokenFormFactory

    darvin_user.password_reset_token.form.handler.class: Darvin\UserBundle\Form\Handler\PasswordResetTokenFormHandler

    darvin_user.password_reset_token.form.renderer.class: Darvin\UserBundle\Form\Renderer\PasswordResetTokenFormRenderer

    darvin_user.password_reset_token.mailer.class: Darvin\UserBundle\PasswordResetToken\PasswordResetTokenMailer

    darvin_user.password_reset_token.requested_listener.class: Darvin\UserBundle\EventListener\PasswordResetTokenRequestedListener

services:
    darvin_user.password_reset_token.factory:
        class: "%darvin_user.password_reset_token.factory.class%"
        arguments:
            - "%darvin_user.password_reset_token_lifetime%"

    darvin_user.password_reset_token.form.factory:
        class: "%darvin_user.password_reset_token.form.factory.class%"
        arguments:
            - "@security.authentication_utils"
            - "@form.factory"
            - "@router"

    darvin_user.password_reset_token.form.handler:
        class: "%darvin_user.password_reset_token.form.handler.class%"
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
            - "@darvin_utils.flash.notifier"
            - "@darvin_user.password_reset_token.factory"
            - "@darvin_user.user.repository"

    darvin_user.password_reset_token.form.renderer:
        class: "%darvin_user.password_reset_token.form.renderer.class%"
        arguments:
            - "@darvin_user.password_reset_token.form.factory"
            - "@templating"

    darvin_user.password_reset_token.mailer:
        class: "%darvin_user.password_reset_token.mailer.class%"
        arguments:
            - "@?darvin_utils.mailer"
            - "@templating"

    darvin_user.password_reset_token.requested_listener:
        class: "%darvin_user.password_reset_token.requested_listener.class%"
        arguments:
            - "@darvin_user.password_reset_token.mailer"
        tags:
            - { name: kernel.event_listener, event: darvin_user.password_reset_token.requested, method: onPasswordResetTokenRequested }
