parameters:
    darvin_user.password_reset_token.form.factory.class: Darvin\UserBundle\Form\Factory\PasswordResetTokenFormFactory

    darvin_user.password_reset_token.form.renderer.class: Darvin\UserBundle\Form\Renderer\PasswordResetTokenFormRenderer

services:
    darvin_user.password_reset_token.form.factory:
        class: %darvin_user.password_reset_token.form.factory.class%
        arguments:
            - "@security.authentication_utils"
            - "@form.factory"
            - "@router"

    darvin_user.password_reset_token.form.renderer:
        class: %darvin_user.password_reset_token.form.renderer.class%
        arguments:
            - "@darvin_user.password_reset_token.form.factory"
            - "@templating"
