parameters:
    darvin_user.profile.controller.change_password.class: Darvin\UserBundle\Controller\Profile\ChangePasswordController

    darvin_user.profile.controller.edit.class: Darvin\UserBundle\Controller\Profile\EditController

    darvin_user.profile.controller.show.class: Darvin\UserBundle\Controller\Profile\ShowController

    darvin_user.profile.form_factory.class: Darvin\UserBundle\Form\Factory\ProfileFormFactory

    darvin_user.profile.form_handler.class: Darvin\UserBundle\Form\Handler\ProfileFormHandler

    darvin_user.profile.form_renderer.class: Darvin\UserBundle\Form\Renderer\ProfileFormRenderer

services:
    _defaults:
        public: true

    darvin_user.profile.controller.change_password:
        class: '%darvin_user.profile.controller.change_password.class%'
        arguments:
            - '@darvin_user.profile.form_factory'
            - '@darvin_user.profile.form_handler'
            - '@darvin_user.profile.form_renderer'
            - '@router'
        tags:
            - { name: controller.service_arguments }

    darvin_user.profile.controller.edit:
        class: '%darvin_user.profile.controller.edit.class%'
        arguments:
            - '@darvin_user.profile.form_factory'
            - '@darvin_user.profile.form_handler'
            - '@darvin_user.profile.form_renderer'
            - '@router'
        tags:
            - { name: controller.service_arguments }

    darvin_user.profile.controller.show:
        class: '%darvin_user.profile.controller.show.class%'
        arguments:
            - '@twig'
            - '@darvin_user.user.manager'
        tags:
            - { name: controller.service_arguments }

    darvin_user.profile.form_factory:
        class: '%darvin_user.profile.form_factory.class%'
        arguments:
            - '@form.factory'
            - '@router'
            - '@darvin_user.user.manager'
            - '%darvin_user.user_class%'

    darvin_user.profile.form_handler:
        class: '%darvin_user.profile.form_handler.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@darvin_utils.flash.notifier'

    darvin_user.profile.form_renderer:
        class: '%darvin_user.profile.form_renderer.class%'
        arguments:
            - '@darvin_user.profile.form_factory'
            - '@twig'
