darvin_user_import_password_reset_token:
    resource: "@DarvinUserBundle/Resources/config/routing/password_reset_token.yml"
    prefix:   /password-reset-token

darvin_user_import_security:
    resource: "@DarvinUserBundle/Resources/config/routing/security.yml"
    prefix:   /
