parameters:
    darvin_user.security.authenticate_user_event_subscriber.class: Darvin\UserBundle\EventListener\AuthenticateUserSubscriber

    darvin_user.security.controller.confirm_registration.class: Darvin\UserBundle\Controller\Security\ConfirmRegistrationController

    darvin_user.security.controller.login.class: Darvin\UserBundle\Controller\Security\LoginController

    darvin_user.security.controller.register.class: Darvin\UserBundle\Controller\Security\RegisterController

    darvin_user.security.controller.reset_password.class: Darvin\UserBundle\Controller\Security\ResetPasswordController

    darvin_user.security.form.factory.class: Darvin\UserBundle\Form\Factory\SecurityFormFactory

    darvin_user.security.form.handler.class: Darvin\UserBundle\Form\Handler\SecurityFormHandler

    darvin_user.security.form.renderer.class: Darvin\UserBundle\Form\Renderer\SecurityFormRenderer

    darvin_user.security.oauth.darvin_auth_user_provider.class: Darvin\UserBundle\Security\OAuth\DarvinAuthUserProvider

    darvin_user.security.twig_extension.class: Darvin\UserBundle\Twig\Extension\SecurityExtension

    darvin_user.security.update_password_event_subscriber.class: Darvin\UserBundle\EventListener\UpdatePasswordSubscriber

    darvin_user.security.user_authenticator.class: Darvin\UserBundle\Security\UserAuthenticator

    darvin_user.security.user_provider.class: Darvin\UserBundle\Security\UserProvider

services:
    darvin_user.security.authenticate_user_event_subscriber:
        class: '%darvin_user.security.authenticate_user_event_subscriber.class%'
        arguments:
            - '@darvin_user.security.user_authenticator'
            - '%darvin_user.public_firewall_name%'
        tags:
            - { name: kernel.event_subscriber }

    darvin_user.security.controller.confirm_registration:
        class: '%darvin_user.security.controller.confirm_registration.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '@twig'
        tags:
            - { name: controller.service_arguments }

    darvin_user.security.controller.login:
        class: '%darvin_user.security.controller.login.class%'
        arguments:
            - '@security.authorization_checker'
            - '@darvin_user.security.form.renderer'
            - '@router'
            - '%darvin_user.already_logged_in_redirect_route%'
        tags:
            - { name: controller.service_arguments }

    darvin_user.security.controller.register:
        class: '%darvin_user.security.controller.register.class%'
        arguments:
            - '@security.authorization_checker'
            - '@darvin_user.security.form.factory'
            - '@darvin_user.security.form.handler'
            - '@darvin_user.security.form.renderer'
            - '@router'
            - '%darvin_user.confirm_registration%'
            - '%darvin_user.already_logged_in_redirect_route%'
        tags:
            - { name: controller.service_arguments }

    darvin_user.security.controller.reset_password:
        class: '%darvin_user.security.controller.reset_password.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@darvin_user.security.form.factory'
            - '@darvin_user.security.form.handler'
            - '@darvin_user.security.form.renderer'
            - '@router'
            - '%darvin_user.already_logged_in_redirect_route%'
        tags:
            - { name: controller.service_arguments }

    darvin_user.security.form.factory:
        class: '%darvin_user.security.form.factory.class%'
        arguments:
            - '@security.authentication_utils'
            - '@form.factory'
            - '@router'
            - '@translator'
            - '@darvin_user.user.factory'
            - '%kernel.secret%'
            - '%darvin_user.user_class%'

    darvin_user.security.form.handler:
        class: '%darvin_user.security.form.handler.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '@darvin_utils.flash.notifier'
            - '@darvin_user.role.configuration'
            - '@darvin_user.security.user_authenticator'
            - '%darvin_user.public_firewall_name%'

    darvin_user.security.form.renderer:
        class: '%darvin_user.security.form.renderer.class%'
        arguments:
            - '@darvin_user.security.form.factory'
            - '@darvin_utils.twig.provider'

    darvin_user.security.oauth.darvin_auth_user_provider:
        class: '%darvin_user.security.oauth.darvin_auth_user_provider.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@security.token_storage'
            - '@darvin_user.user.factory'
            - '@darvin_user.user.repository'

    darvin_user.security.twig_extension:
        class: '%darvin_user.security.twig_extension.class%'
        arguments:
            - '@darvin_user.security.form.factory'
            - '@darvin_user.security.form.renderer'
        tags:
            - { name: twig.extension }

    darvin_user.security.update_password_event_subscriber:
        class: '%darvin_user.security.update_password_event_subscriber.class%'
        arguments:
            - '@darvin_user.user.manager'
        tags:
            - { name: doctrine.event_subscriber }

    darvin_user.security.user_authenticator:
        class: '%darvin_user.security.user_authenticator.class%'
        arguments:
            - '@security.token_storage'

    darvin_user.security.user_provider:
        class: '%darvin_user.security.user_provider.class%'
        arguments:
            - '@darvin_user.user.repository'
