parameters:
    darvin_user.security.configuration.class: Darvin\UserBundle\Security\SecurityConfiguration

services:
    darvin_user.security.configuration:
        class: %darvin_user.security.configuration.class%
        tags:
            - { name: darvin_config.configuration }
            - { name: darvin_admin.security_configuration }
