parameters:
    darvin_user.user.event_subscriber.class: Darvin\UserBundle\EventListener\UserSubscriber

    darvin_user.user.form.factory.class: Darvin\UserBundle\Form\Factory\UserFormFactory

    darvin_user.user.form.handler.class: Darvin\UserBundle\Form\Handler\UserFormHandler

    darvin_user.user.form.renderer.class: Darvin\UserBundle\Form\Renderer\UserFormRenderer

    darvin_user.user.mailer.class: Darvin\UserBundle\User\UserMailer

    darvin_user.user.manager.generic.class: Darvin\UserBundle\User\GenericUserManager

    darvin_user.user.validator.user_exists_and_active.class: Darvin\UserBundle\Validator\UserExistsAndActiveValidator

services:
    darvin_user.user.event_subscriber:
        class:  %darvin_user.user.event_subscriber.class%
        public: false
        arguments:
            - "@darvin_user.user.manager"
        tags:
            - { name: doctrine.event_subscriber }

    darvin_user.user.form.factory:
        class: %darvin_user.user.form.factory.class%
        arguments:
            - "@form.factory"
            - "@router"
            - "@darvin_user.user.manager"

    darvin_user.user.form.handler:
        class: %darvin_user.user.form.handler.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@darvin_utils.flash.notifier"

    darvin_user.user.form.renderer:
        class: %darvin_user.user.form.renderer.class%
        arguments:
            - "@templating"
            - "@darvin_user.user.form.factory"

    darvin_user.user.mailer:
        class: %darvin_user.user.mailer.class%
        arguments:
            - "@darvin_utils.mailer"
            - "@templating"
            - "@darvin_user.configuration"

    darvin_user.user.manager:
        alias: darvin_user.user.manager.generic

    darvin_user.user.manager.generic:
        class: %darvin_user.user.manager.generic.class%
        arguments:
            - "@security.token_storage"
            - "@security.password_encoder"

    darvin_user.user.validator.user_exists_and_active:
        class: %darvin_user.user.validator.user_exists_and_active.class%
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: darvin_user_user_exists_and_active }
