parameters:
    darvin_user.user.event_subscriber.class: Darvin\UserBundle\EventListener\UserSubscriber

    darvin_user.user.manager.generic.class: Darvin\UserBundle\User\GenericUserManager

    darvin_user.user.validator.user_exists_and_active.class: Darvin\UserBundle\Validator\UserExistsAndActiveValidator

services:
    darvin_user.user.event_subscriber:
        class:  %darvin_user.user.event_subscriber.class%
        public: false
        arguments:
            - "@darvin_user.user.manager"
        tags:
            - { name: doctrine.event_subscriber }

    darvin_user.user.manager:
        alias: darvin_user.user.manager.generic

    darvin_user.user.manager.generic:
        class: %darvin_user.user.manager.generic.class%
        arguments:
            - "@security.token_storage"
            - "@security.password_encoder"

    darvin_user.user.validator.user_exists_and_active:
        class: %darvin_user.user.validator.user_exists_and_active.class%
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: validator.constraint_validator, alias: darvin_user_user_exists_and_active }
