parameters:
    darvin_user.configuration.class: Darvin\UserBundle\Config\UserConfig

services:
    darvin_user.configuration:
        class: '%darvin_user.configuration.class%'
        arguments:
            - '%darvin_user.mailer.enabled%'
        tags:
            - { name: darvin_config.configuration }
