parameters:
    darvin_user.mailer.factory.password_reset.class: Darvin\UserBundle\Mailer\Factory\PasswordResetEmailFactory

    darvin_user.mailer.subscriber.send.password_reset.class: Darvin\UserBundle\EventListener\Mailer\SendPasswordResetEmailsSubscriber

    darvin_user.mailer.send_registered_emails_event_subscriber.class: Darvin\UserBundle\EventListener\Mailer\SendRegisteredEmailsSubscriber

    darvin_user.mailer.user.class: Darvin\UserBundle\Mailer\UserMailer

services:
    darvin_user.mailer.factory.password_reset:
        class: '%darvin_user.mailer.factory.password_reset.class%'
        arguments:
            - '@darvin_mailer.factory.template'

    darvin_user.mailer.subscriber.send.password_reset:
        class: '%darvin_user.mailer.subscriber.send.password_reset.class%'
        arguments:
            - '@darvin_user.mailer.factory.password_reset'
            - '@darvin_mailer.mailer'
        tags:
            - { name: kernel.event_subscriber }

    darvin_user.mailer.send_registered_emails_event_subscriber:
        class: '%darvin_user.mailer.send_registered_emails_event_subscriber.class%'
        arguments:
            - '@darvin_user.mailer.user'
        tags:
            - { name: kernel.event_subscriber }

    darvin_user.mailer.user:
        class: '%darvin_user.mailer.user.class%'
        arguments:
            - '@darvin_mailer.template_mailer'
            - '@?darvin_user.configuration'
