parameters:
    darvin_user.mailer.factory.password_reset.class: Darvin\UserBundle\Mailer\Factory\PasswordResetEmailFactory

    darvin_user.mailer.factory.user.class: Darvin\UserBundle\Mailer\Factory\UserEmailFactory

    darvin_user.mailer.subscriber.send.password_reset.class: Darvin\UserBundle\EventListener\Mailer\SendPasswordResetEmailsSubscriber

    darvin_user.mailer.subscriber.send.registered.class: Darvin\UserBundle\EventListener\Mailer\SendRegisteredEmailsSubscriber

services:
    Darvin\UserBundle\Mailer\Factory\PasswordResetEmailFactoryInterface: '@darvin_user.mailer.factory.password_reset'
    Darvin\UserBundle\Mailer\Factory\UserEmailFactoryInterface:          '@darvin_user.mailer.factory.user'

    darvin_user.mailer.factory.password_reset:
        class: '%darvin_user.mailer.factory.password_reset.class%'
        arguments:
            - '@darvin_mailer.factory.template'

    darvin_user.mailer.factory.user:
        class: '%darvin_user.mailer.factory.user.class%'
        arguments:
            - '@darvin_mailer.factory.template'
            - '@?darvin_user.configuration'

    darvin_user.mailer.subscriber.send.password_reset:
        class: '%darvin_user.mailer.subscriber.send.password_reset.class%'
        arguments:
            - '@darvin_user.mailer.factory.password_reset'
            - '@darvin_mailer.mailer'
        tags:
            - { name: kernel.event_subscriber }

    darvin_user.mailer.subscriber.send.registered:
        class: '%darvin_user.mailer.subscriber.send.registered.class%'
        arguments:
            - '@darvin_user.mailer.factory.user'
            - '@darvin_mailer.mailer'
        tags:
            - { name: kernel.event_subscriber }
