parameters:
    darvin_user.role.choice_form_type.class: Darvin\UserBundle\Form\Type\RoleChoiceType

    darvin_user.role.configuration.class: Darvin\UserBundle\Config\RoleConfig

services:
    Darvin\UserBundle\Config\RoleConfigInterface: '@darvin_user.role.configuration'

    darvin_user.role.choice_form_type:
        class: '%darvin_user.role.choice_form_type.class%'
        arguments:
            - '@security.authorization_checker'
            - '@darvin_user.role.configuration'
        tags:
            - { name: form.type }

    darvin_user.role.configuration:
        class: '%darvin_user.role.configuration.class%'
        arguments:
            - '%darvin_user.roles%'
