parameters:
    darvin_user.user.create_command.class: Darvin\UserBundle\Command\UserCreateCommand
    darvin_user.user.create_command.name:  darvin:user:create

    darvin_user.user.factory.class: Darvin\UserBundle\User\UserFactory

    darvin_user.user.manager.class: Darvin\UserBundle\User\UserManager

    darvin_user.user.repository.class: Darvin\UserBundle\Repository\UserRepository

    darvin_user.user.validator.user_exists_and_active.class: Darvin\UserBundle\Validator\UserExistsAndActiveValidator

services:
    Darvin\UserBundle\User\UserFactoryInterface: '@darvin_user.user.factory'
    Darvin\UserBundle\User\UserManagerInterface: '@darvin_user.user.manager'

    darvin_user.user.create_command:
        class: '%darvin_user.user.create_command.class%'
        arguments:
            - '%darvin_user.user.create_command.name%'
            - '@doctrine.orm.entity_manager'
            - '@darvin_user.role.configuration'
            - '@darvin_user.user.factory'
            - '@validator'
        tags:
            - { name: console.command }

    darvin_user.user.factory:
        class:  '%darvin_user.user.factory.class%'
        public: true
        arguments:
            - '%darvin_user.user_class%'

    darvin_user.user.manager:
        class: '%darvin_user.user.manager.class%'
        arguments:
            - '@security.token_storage'
            - '@security.password_encoder'

    darvin_user.user.repository:
        alias: Darvin\UserBundle\Repository\UserRepository

    Darvin\UserBundle\Repository\UserRepository:
        class: '%darvin_user.user.repository.class%'
        arguments:
            - '@doctrine'
            - '%darvin_user.user_class%'
        tags:
            - { name: doctrine.repository_service }

    darvin_user.user.validator.user_exists_and_active:
        class: '%darvin_user.user.validator.user_exists_and_active.class%'
        arguments:
            - '@darvin_user.user.repository'
        tags:
            - { name: validator.constraint_validator, alias: darvin_user_user_exists_and_active }
