entity_name: user
disabled_routes:
    - copy
images:
    homepage_menu_icon: bundles/darvinuser/images/icons/homepage/user.png
menu:
    color:    "#2171ac"
    position: 0
sortable_fields:
    email:   ~
    locked:  ~
    enabled: ~
    roles:   ~
form:
    edit:
        fields:
            locked:
                options:
                    required: false
            enabled:
                options:
                    required: false
            email: ~
            plainPassword:
                options:
                    required: false
            roles:
                type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
                options:
                    choices:  [ Darvin\UserBundle\Entity\BaseUser, getExtraRoles ]
                    multiple: true
                    expanded: true
    filter:
        fields:
            email:
                compare_strict: false
            enabled: ~
            locked:  ~
            roles:
                type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
                options:
                    choices: [ Darvin\UserBundle\Entity\BaseUser, getExtraRoles ]
                compare_strict: false
    index:
        fields:
            locked:  ~
            enabled: ~
    new:
        fields:
            locked:
                options:
                    required: false
            enabled:
                options:
                    required: false
            email:         ~
            plainPassword: ~
            roles:
                type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
                options:
                    choices:  [ Darvin\UserBundle\Entity\BaseUser, getExtraRoles ]
                    multiple: true
                    expanded: true
view:
    index:
        fields:
            email:
                widget:
                    alias: email_link
            locked:  ~
            enabled: ~
            roles:
                widget:
                    alias: compound_list
                    options:
                        values_callback: [ Darvin\UserBundle\Entity\BaseUser, getExtraRoles ]
    show:
        fields:
            email:
                widget:
                    alias: email_link
            locked:  ~
            enabled: ~
            roles:
                widget:
                    alias: compound_list
                    options:
                        values_callback: [ Darvin\UserBundle\Entity\BaseUser, getExtraRoles ]
