searchable_fields:
    - username
    - email
sortable_fields:
    username: ~
    email:    ~
    enabled:  ~
    locked:   ~
    roles:    ~
menu:
    position: 990
    colors:
        main:    '#2171ac'
        sidebar: '#48aef9'
    icons:
        main:    bundles/darvinuser/images/admin/user_main.png
        sidebar: bundles/darvinuser/images/admin/user_sidebar.png
view:
    index:
        action_widgets:
            show_link:   ~
            switch_user: ~
            edit_link:   ~
            delete_form: ~
        fields:
            username: ~
            email:
                widget: email_link
            enabled: ~
            locked:  ~
            roles:
                widget:    user_roles
                condition: 'is_granted("ROLE_SUPER_ADMIN")'
    extend~index~show:
        override~action_widgets:
            switch_user: ~
            edit_link:   ~
            delete_form: ~
form:
    index:
        fields:
            enabled: ~
            locked:  ~
    filter:
        fields:
            username:
                compare_strict: false
            email:
                compare_strict: false
            enabled: ~
            locked:  ~
            roles:
                type:           Darvin\UserBundle\Form\Type\RoleChoiceType
                condition:      'is_granted("ROLE_SUPER_ADMIN")'
                compare_strict: false
    new:
        fields:
            enabled:
                options:
                    required: false
            locked:
                options:
                    required: false
            email: ~
            username:
                options:
                    required: false
            plainPassword:
                type: password
            roles:
                type:      Darvin\UserBundle\Form\Type\RoleChoiceType
                condition: 'is_granted("ROLE_SUPER_ADMIN")'
                options:
                    multiple: true
                    required: false
    extend~new~edit:
        fields:
            plainPassword:
                options:
                    required: false
