disabled_routes:
    - copy
searchable_fields:
    - email
sortable_fields:
    email:   ~
    locked:  ~
    enabled: ~
    roles:   ~
menu:
    position: 0
    colors:
        main:    "#2171ac"
        sidebar: "#48aef9"
    icons:
        main:    bundles/darvinuser/images/admin/user_main.png
        sidebar: bundles/darvinuser/images/admin/user_sidebar.png
form:
    edit:
        fields:
            locked:
                options:
                    required: false
            enabled:
                options:
                    required: false
            email: ~
            plainPassword:
                type: Symfony\Component\Form\Extension\Core\Type\PasswordType
                options:
                    required: false
            roles:
                type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
                options:
                    choices:  [ Darvin\UserBundle\Entity\BaseUser, getExtraRoles ]
                    multiple: true
                    expanded: true
    filter:
        fields:
            email:
                compare_strict: false
            enabled: ~
            locked:  ~
            roles:
                type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
                options:
                    choices: [ Darvin\UserBundle\Entity\BaseUser, getExtraRoles ]
                compare_strict: false
    index:
        fields:
            locked:  ~
            enabled: ~
    new:
        fields:
            locked:
                options:
                    required: false
            enabled:
                options:
                    required: false
            email: ~
            plainPassword:
                type: Symfony\Component\Form\Extension\Core\Type\PasswordType
            roles:
                type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
                options:
                    choices:  [ Darvin\UserBundle\Entity\BaseUser, getExtraRoles ]
                    multiple: true
                    expanded: true
view:
    index:
        fields:
            email:
                widget:
                    alias: email_link
            locked:  ~
            enabled: ~
            roles:
                widget:
                    alias: compound_list
                    options:
                        values_callback: [ Darvin\UserBundle\Entity\BaseUser, getExtraRoles ]
    show:
        fields:
            email:
                widget:
                    alias: email_link
            locked:  ~
            enabled: ~
            roles:
                widget:
                    alias: compound_list
                    options:
                        values_callback: [ Darvin\UserBundle\Entity\BaseUser, getExtraRoles ]
