menu:
    position: 990

searchable_fields:
    - username
    - email

sortable_fields:
    username: ~
    email:    ~
    enabled:  ~
    locked:   ~
    roles:    ~

view:
    index:
        extra_action_widgets:
            switch_user: ~
        fields:
            username: ~
            email:
                widget: email_link
            enabled: ~
            locked:  ~
            roles:
                widget: user_roles

form:
    index:
        fields:
            enabled: ~
            locked:  ~
    filter:
        fields:
            username:
                compare_strict: false
            email:
                compare_strict: false
            enabled: ~
            locked:  ~
            roles:
                type:           Darvin\UserBundle\Form\Type\RoleChoiceType
                compare_strict: false
    new:
        fields:
            enabled:
                options:
                    required: false
            locked:
                options:
                    required: false
            email: ~
            plainPassword:
                type: password
            roles:
                type: Darvin\UserBundle\Form\Type\RoleChoiceType
                options:
                    multiple: true
                    required: false
            username:
                options:
                    help:     user.help.username
                    required: false
    extend~new~edit:
        fields:
            plainPassword:
                options:
                    required: false
