joins:
    password_reset_token: passwordResetToken
searchable_fields:
    - email
sortable_fields:
    email:   ~
    enabled: ~
    locked:  ~
    roles:   ~
menu:
    position: 0
    colors:
        main:    "#2171ac"
        sidebar: "#48aef9"
    icons:
        main:    bundles/darvinuser/images/admin/user_main.png
        sidebar: bundles/darvinuser/images/admin/user_sidebar.png
form:
    index:
        fields:
            enabled: ~
            locked:  ~
    filter:
        fields:
            email:
                compare_strict: false
            enabled: ~
            locked:  ~
            roles:
                type:           Darvin\UserBundle\Form\Type\User\RoleChoiceType
                compare_strict: false
    edit:
        fields:
            enabled:
                options:
                    required: false
            locked:
                options:
                    required: false
            email: ~
            plainPassword:
                type: password
                options:
                    required: false
            roles:
                type: Darvin\UserBundle\Form\Type\User\RoleChoiceType
                options:
                    multiple: true
                    required: false
    new:
        fields:
            enabled:
                options:
                    required: false
            locked:
                options:
                    required: false
            email: ~
            plainPassword:
                type: password
            roles:
                type: Darvin\UserBundle\Form\Type\User\RoleChoiceType
                options:
                    multiple: true
                    required: false
view:
    index:
        action_widgets:
            show_link:   ~
            edit_link:   ~
            delete_form: ~
            switch_user: ~
        fields:
            email:
                widget:
                    alias: email_link
            enabled: ~
            locked:  ~
            roles:
                widget:
                    alias: user_roles
    show:
        action_widgets:
            edit_link:   ~
            delete_form: ~
            switch_user: ~
        fields:
            email:
                widget:
                    alias: email_link
            enabled: ~
            locked:  ~
            roles:
                widget:
                    alias: user_roles
