parameters:
    darvin_user.configuration.roles.class: Darvin\UserBundle\Configuration\RoleConfiguration

services:
    _defaults:
        public: true

    darvin_user.configuration.roles:
        class: '%darvin_user.configuration.roles.class%'
        arguments:
            - '%darvin_user.roles%'
