hwi_oauth:
    firewall_names:
        - public_area
    resource_owners:
        darvin_auth:
            type:                oauth2
            client_id:           '%env(resolve:DARVIN_AUTH_CLIENT_ID)%'
            client_secret:       '%env(resolve:DARVIN_AUTH_CLIENT_SECRET)%'
            access_token_url:    https://auth.darvins.ru/oauth/v2/token
            authorization_url:   https://auth.darvins.ru/oauth/v2/auth
            infos_url:           https://auth.darvins.ru/api/user
            user_response_class: Darvin\UserBundle\Security\OAuth\DarvinAuthResponse
            options:
                csrf: true
            paths:
                email:          email
                identifier:     username
                nickname:       username
                profilepicture: picture
                realname:       fullname
                # Additional
                error:          error
                gender:         gender
                phone:          phone
                position:       position
                roles:          roles
                skype:          skype
