darvin_user_security_darvin_auth_login_check:
    path: /login/darvin-auth/check

darvin_user_security_login_check:
    path: /login/check

darvin_user_security_login:
    path:     /login
    defaults: { _controller: DarvinUserBundle:Security:login }

darvin_user_security_darvin_auth_login:
    path:     /login/{service}
    defaults: { _controller: HWIOAuthBundle:Connect:redirectToService }

darvin_user_security_logout:
    path: /logout

darvin_user_security_register:
    path:     /register
    defaults: { _controller: DarvinUserBundle:Security:register }

darvin_user_security_reset_password:
    path:     /reset-password
    defaults: { _controller: DarvinUserBundle:Security:resetPassword }
