darvin_user_security_login:
    path:     /login
    defaults: { _controller: DarvinUserBundle:Security:login }

darvin_user_security_login_check:
    path: /login-check

darvin_user_security_logout:
    path: /logout

darvin_user_security_register:
    path:     /register
    defaults: { _controller: DarvinUserBundle:Security:register }
