darvin_user_security_darvin_auth_login_check:
    path:    /login/darvin-auth/check
    methods: [ get ]

darvin_user_security_login_check:
    path:    /login/check
    methods: [ post ]

darvin_user_security_login:
    path:     /login
    defaults: { _controller: darvin_user.security.controller.login }
    methods:  [ get ]

darvin_user_security_darvin_auth_login:
    path:     /login/{service}
    defaults: { _controller: HWI\Bundle\OAuthBundle\Controller\RedirectToServiceController::redirectToServiceAction }
    methods:  [ get ]

darvin_user_security_logout:
    path:    /logout
    methods: [ get ]

darvin_user_security_register:
    path:     /register
    defaults: { _controller: darvin_user.security.controller.register }
    methods:  [ get, post ]

darvin_user_security_reset_password:
    path:     /reset-password
    defaults: { _controller: darvin_user.security.controller.reset_password }
    methods:  [ get, post ]

darvin_user_security_confirm_registration:
    path:     /register/confirm/{code}
    defaults: { _controller: darvin_user.security.controller.confirm_registration, code: null }
    methods:  [ get ]
